### ISSUE TITLE
powerPreference shouldn't be boolean

### ISSUE THREAD

**Issue by ricklamers** [pixijs/bunny-mark#4]
I was trying bunny-mark in Safari (Version 11.0.3 (13604.5.6)) on High Sierra 10.13.3 Beta.

I noticed a Type error. Turns out it's because the powerPreference is filled with a boolean value because of the checkbox in the input form. I think it should be a string 'default', 'high-performance' or 'low-power' based on the spec (https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1).

Not sure how to change the HTML form to make it more sensible, couldn't easily figure out where and how the form is parsed and passed to the initialization of the Pixi canvas.

**Comment by NikkiKoole** [comment]
Ive made a PR for this issue
https://github.com/pixijs/bunny-mark/pull/5

**Comment by englercj** [comment]
Looks like it was merged :)

**Comment by bigtimebuddy** [comment]
I cleaned up some of the CSS and pushed a new version to https://pixijs.io/bunny-mark
Thanks for digging into this.

**Comment by NikkiKoole** [comment]
@bigtimebuddy  there was a new related issue with the changes, there are more then 1 selects on the page now, resulting in the wrong value being put in the options ('' instead of 'default')
made a new PR for it.
