### ISSUE TITLE
Test doesn't start with new versions of Pixi.js

### ISSUE THREAD

**Issue by nathan-knight** [pixijs/bunny-mark#7]
Attempting to run the test with all the default settings against the dev branch results in the test breaking with this error:
```
Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at BunnyMark.ready (index.js:228)
    at VersionChooser.stop (index.js:670)
    at VersionChooser.update (index.js:655)
```

It is checking if the renderer is an instance of `PIXI.CanvasRenderer` and my guess is that that is not bundled with what it is pulling due to the split between `pixi.js` and `pixi.js-legacy`.

**Comment by bigtimebuddy** [comment]
Cannot repro. Assuming this is now fixed.
